- main.go
- pkg/kube/resources.go
There were a number of places where errors were not being logged or displayed, this should fix a bunch of them.
> Improving error handling

- .dockerignore
- deploy/dashboard.yaml
- deploy/helm/polaris/templates/dashboard.deployment.yaml
- deploy/helm/polaris/templates/webhook.deployment.yaml
- deploy/webhook.yaml
When we embedded the Polaris config into the binary with packr, we failed to update the deployment config to actually point to the Polaris config we were mounting in to the pod with a configmap. That meant that if changed a value in the configmap, it wouldn't actually change the Polaris config being used, this should fix that.
> Referencing Polaris config file as part of deployment config

- pkg/validator/container.go
- pkg/validator/container_test.go
Although resource requests and limits can sometimes make sense for init containers, they usually do not. Because of that (originally mentioned by #125), we're going to ignore those checks by default for init containers. In the future it may make sense to allow this validation to be optionally enabled.
> Adding exception for init container resource checks

- README.md
- main.go
- pkg/dashboard/assets/css/Muli.css
- pkg/dashboard/dashboard.go
- pkg/dashboard/templates/check-details.gohtml
- pkg/dashboard/templates/dashboard.gohtml
- pkg/dashboard/templates/head.gohtml
- pkg/dashboard/templates/navbar.gohtml
> optionalize base path for dashboard

- CONTRIBUTING.md
**What this PR does and why we need it** 
This PR adds instructions for how to run Polaris locally so people can setup the project on their computer. This will lower the barrier to entry for contributors that are outside of ReactiveOps. 
**Please note** 
I had to sign a CLA in order to work on the project, but I cannot find a link for it, so the 'Contributor License Agreement' url is blank. Please let me know where I can find that info.
> add instructions for local development 

- README.md
- main.go
- pkg/dashboard/dashboard.go
- pkg/dashboard/helpers.go
- pkg/dashboard/templates/dashboard.gohtml
- pkg/validator/fullaudit.go
- pkg/validator/types.go
Goal here was better support for CI/CD, but it ended up being a bit of a rabbit hole.
A few notes:
* Changed YAML marshaler to one that formats consistently with JSON marshaler
* Added score to output
* Added `output-format` which can be `json`, `yaml`, or `score` - the last option there just prints the overall score, e.g. `93`
* Changes to docs
> Better support for CI/CD use case

- deploy/helm/polaris/templates/dashboard.deployment.yaml
- main.go
- pkg/config/config.go
- pkg/dashboard/assets/css/dashboard.css
- pkg/dashboard/templates/dashboard.gohtml
- pkg/kube/resources.go
- pkg/kube/resources_test.go
- pkg/validator/fullaudit.go
- pkg/validator/fullaudit_test.go
Addresses https://github.com/reactiveops/polaris/issues/124
Uses whatever the user specifies as `--cluster-name`, falling back to the `host` named in kubeconfig. Doesn't look like we can get the `name` field: https://github.com/kubernetes/client-go/issues/530  
Any potential issues with surfacing the `host` in the dashboard? E.g. could it have basic auth creds?
Here's what it looks like:
> Show cluster name/host on dashboard

- pkg/kube/resources.go
Fixes issue [#141](https://github.com/reactiveops/polaris/issues/141)
**What this PR does and why we need it**
I updated the `CreateResourceProviderFromCluster` function to find the KubeConfig and return an error if there is an issue retrieving the data. I wasn't able to figure out how to return the empty `ResourceProvider`, so I returned `nil` instead. Let me know if the empty `ResourceProvider` is necessary and I'll figure that out. 
See line 132 for the specific line I'm referring to: https://github.com/reactiveops/polaris/compare/ks/adjust-os-exit?expand=1#diff-5524e4ddda8206adfe02f6a98ed7160eR132
> adjust os exit

- main.go
**What this PR does** 
This PR creates an `--set-exit-code-on-error` flag. If the user runs an audit and passes in this flag, the audit will exit with a status code of `3`. This functionality is most helpful for CI/CD use cases. 
**This PR addresses issue** [143](https://github.com/reactiveops/polaris/issues/143)
> Add exit code flag 

- .circleci/config.yml
- CONTRIBUTING.md
- README.md
- deploy/dashboard.yaml
- deploy/webhook.yaml
Slight hiccup with this process: the new deploy.yaml will get checked in before the images are built. So there will be a 10-15 minute period of breakage.
Maybe it'd be better to tag the commit *before* it gets merged - that way images are built ahead of time. And we can run goreleaser only once that tag is merged into master.
Thoughts?
> add deploy configurations to source control

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/other.md
- CONTRIBUTING.md
I've added issues templates for bug reports, feature requests and other as a response to feedback left on this PR: https://github.com/FairwindsOps/polaris/pull/168. 
The goal of these templates is to better organize our issues, as well as encourage folks who are filing a bug report to check their version of polaris and update when necessary.
> Add issue templates

- pkg/validator/container.go
- pkg/validator/container_test.go
> pass RunAsNonRoot if RunAsUser > 0

- checks/hostIPC.yaml
- checks/hostNetwork.yaml
- checks/hostPID.yaml
- checks/hostPortSet.yaml
- checks/host_network.yaml
- checks/livenessProbe.yaml
- checks/notReadOnlyRootFileSystem.yaml
- checks/privilegeEscalationAllowed.yaml
- checks/pullPolicyNotAlways.yaml
- checks/readinessProbe.yaml
- checks/runAsPrivileged.yaml
- checks/runAsRootAllowed.yaml
- checks/tagNotSpecified.yaml
- pkg/config/exemptions.go
- pkg/config/supportedcontrollers.go
- pkg/config/supportedcontrollers_test.go
- pkg/validator/container.go
- pkg/validator/container_test.go
- pkg/validator/controller.go
- pkg/validator/pod.go
- pkg/validator/schema.go
- pkg/webhook/validator.go
This is step 1 toward supporting custom checks written in JSON schema.
I think rewriting many of our current checks using JSON schema will help clean up the codebase a bunch too.
> JSON schema checks

- README.md
updating language around the webhook because admission controller is what people are really searching for, not webhook
> Change webhook language to admission controller

- docs/usage.md
charts.fairwindsops.com doesn't resolve, fixed according to https://github.com/FairwindsOps/charts
> Fix chart repository name in docs

- .gitignore
- pkg/config/exemptions.go
- pkg/config/exemptions_test.go
This adds the ability to exempt a controller from all checks similar to
the annotation for "exempt" which exempts all checks.
I added the tests to go with this as well as for the IsActionable
function.
Validation Commands:
```bash
[3:36:45] ~/go/src/github.com/fairwindsops/polaris [add_controller_wide_exemption] λ go list ./... | grep -v vendor | xargs golint -set_exit_status
[3:39:09] ~/go/src/github.com/fairwindsops/polaris [add_controller_wide_exemption] λ echo $?
0
[3:39:19] ~/go/src/github.com/fairwindsops/polaris [add_controller_wide_exemption] λ go list ./... | grep -v vendor | xargs go vet
[3:39:31] ~/go/src/github.com/fairwindsops/polaris [add_controller_wide_exemption] λ echo $?
0
[3:39:40] ~/go/src/github.com/fairwindsops/polaris [add_controller_wide_exemption] λ go test …
```
> Adds option to exempt an entire controller from checks via config file

- docs/usage.md
- pkg/kube/resources.go
- pkg/kube/resources_test.go
Closes #250
Usage:
```
cat pod.yaml | polaris audit --audit-path -
```
> Support read yaml contents of workload from stdin

- pkg/dashboard/templates/dashboard.gohtml
As I mentioned in https://github.com/FairwindsOps/polaris/issues/351,
custom check results for `target: Controller` have not been shown on the
Dashboard.
> Show controller check results on dashboard

- docs/usage.md
Actual flag: https://github.com/FairwindsOps/polaris/blob/2ac6a2b54029f155f6ca696fbd430b398686241f/cmd/polaris/audit.go#L46
> Fix CLI flags documentation

- cmd/polaris/audit.go
- docs/usage.md
- pkg/dashboard/dashboard.go
- pkg/kube/resources.go
- pkg/kube/workload.go
Sadly I haven't been able to test this - I can't get DynamicClient to work properly in test mode. Any ideas would be appreciated.
> add ability to audit a single workload

- docs/usage.md
- examples/config-full.yaml
- examples/config.yaml
- pkg/config/config.go
- pkg/config/exemptions.go
- pkg/config/exemptions_test.go
- pkg/config/schema.go
- pkg/validator/schema.go
Add namespace support for exceptions for shared clusters.
> Implement namespace support for exceptions

- checks/multipleReplicasForDeployment.yaml
- docs-md/changelog.md
- pkg/kube/workload.go
This fixes an inconsistency in how controller-level checks are handled between IaC and in-cluster resources.
The in-cluster resources had an `Object` wrapper around the JSON - this removes that.
This will need a major version bump.
Still working on testing this properly - our k8s mocks aren't quite working right.
> change how controller checks are handled

- docs-md/admission-controller.md
Recommend updating the install document to be more clear about the use of cert-manager and also updating the name of the  helm chart repository to reflect "fairwinds" rather than "fairwindsOps".
> Install Doc Updates

- pkg/dashboard/assets/js/charts.js
- pkg/dashboard/helpers.go
- pkg/dashboard/templates/dashboard.gohtml
- pkg/validator/summary.go
This fixes a few issues when there are zero checks for a particular resource:
* the resource now gets a score of 100% instead of 0%
* the UI now shows green instead of red
* subsections will show `no checks available` instead of just being empty
> Fix up zero-score issues

- checks/insecureCapabilities.yaml
- checks/privilegeEscalationAllowed.yaml
- pkg/validator/container_test.go
- test/checks/insecureCapabilities/failure.drop-most.yaml
- test/checks/insecureCapabilities/failure.yaml
- test/checks/insecureCapabilities/success.drop.yaml
- test/checks/insecureCapabilities/success.yaml
- test/checks/privilegeEscalationAllowed/failure.unspecified.yaml
- test/checks/privilegeEscalationAllowed/failure.yaml
- test/checks/privilegeEscalationAllowed/success.yaml
These capabilities are on-by-default, so they need to be dropped, not just not-added.
> fix checks for k8s defaults

- cmd/polaris/root.go
- docs/cli.md
- pkg/config/config.go
- pkg/config/exemptions.go
- pkg/dashboard/dashboard.go
- pkg/validator/schema.go
This change follows up #635 and lets end-users decide to disallow exemption rules defined as part of the config file or the controller annotations (whether none, any or both). The main use case here is to be able to prevent users with edit privileges over a controller to add a new exemption rule through an annotation which may obfuscate the actual policies we want to enforce.
> config: new flags '--disallow-(config|annotation)-exemptions'

- .circleci/config.yml
The homebrew release should not include `bottle :unneeded` as it is
deprecated. This is fixed in goreleaser.
> Update goreleaser to v1.1.0

- .circleci/config.yml
- .goreleaser.yml
- get publish secrets from vault.
- Update goreleaser.
- Sign checksums with cosign
- Enable experimental docker features to move towards multi-arch support
Move towards some of our more modern CI/CD standards
> CI/CD Updates

- .gitignore
- pkg/kube/resource.go
CRD's cause issues with finding out the pod security contexts of them (since they might be wrapped in a different format than "containers" array
After discussion on slack, added an exclusion list for quick exiting at final state for deployments, daemonsets, cronjobs, etc...
ref: https://fairwindscommunity.slack.com/archives/CURU6LA91/p1647271688336659
Parse and dissect the meta data from a release of a helm chart, or work backwards from parents back to children once no resources are discovered on the parent chart.
> bounce out once we hit a type we know to avoid CRD problems

- cmd/polaris/audit.go
- docs/cli.md
Signed-off-by: krrrr38 <k.kaizu38@gmail.com>
audit command should check only specific checks
In https://github.com/FairwindsOps/polaris/pull/712, added new `checks` args into audit command, but not used.
I change it as string slice variable and change check severity as Ignored when passing checks args.
N/A
<details>
<summary>before: not filtered checks</summary>
```
> go run main.go audit -f pretty --audit-path /path/to/templatesNodeSelectorNodeTypeWorkflowTemplate/success.yaml --config /path/to/.polaris.yaml --set-exit-code-on-danger --log-level error --checks templatesNodeSelectorNodeTypeWorkflowTemplate,b --checks a
Polaris audited Path /path/to/templatesNodeSelectorNodeTypeWorkflowTemplate/success.yaml at 2022-03-31T09:11:39+09:00
Nodes: 0 | Namespaces: 0 | Controllers: 0
Final score: …
```
> audit check specific checks when passing checks args

- examples/config-full.yaml
- examples/config.yaml
- pkg/kube/resource.go
- pkg/kube/resources.go
- pkg/validator/arbitrary_test.go
This PR fixes # https://github.com/FairwindsOps/polaris/issues/725
Sometimes the ultimate owner of a Pod does not contain a `podSpec`. Examples include the Prometheus Operator's`Prometheus` CRD and Argo's `Rollout` CRD.
The goal here is to make sure we still capture pod-level findings for these resources.
* Remove `isFinalKind`, which was an overly-specific heuristic for fixing this issue for the Prometheus CRD
* Track the most recent `podSpec` as we walk up the owner hierarchy. If we reach a resource that doesn't have a `podSpec`, use the one from its child
I think this is probably the best solution
> Save last podspec when walking owner hierarchy

- cmd/polaris/webhook.go
- go.mod
- pkg/config/schema.go
- pkg/mutation/mutate.go
- pkg/validator/output.go
- pkg/validator/schema.go
- pkg/webhook/mutate.go
- pkg/webhook/webhook.go
It adds `/mutate`  endpoint for mutating Kubernetes resources.
Goal is to be able to mutate k8s resources based on the rules and mutations defined.
> Added Mutation webhook 

- cmd/polaris/webhook.go
Only enable mutations when a flag is set
Added a `--mutate` flag
> Add flag to enable mutations in webhook

- pkg/config/schema.go
- pkg/kube/resource.go
- pkg/kube/resources.go
- pkg/validator/polaris_template_variable_test.go
- pkg/validator/schema.go
This PR fixes #735 
Add a `target: PodTemplate` to make the full pod (not only the spec) available to schema-checking.
Added a new target `PodTemplate`, a function `GetPodTemplate` to return the complete pod containing `spec.containers`, and updated other logic to process the new `target: PodTemplate`.
> Add `target PodTemplate` which exposes the full Pod (not only the spec)

- pkg/kube/resources.go
Polaris checks for `additionalSchemaStrings` involving a Kube resource with no APIGroup were failing unexpectedly.
After further troubleshooting, when a Polaris check `additionalSchemaStrings` looks up a Kube resource with no APIGroup (such as ServiceAccount), those resources were not retained in the `ResourceProvider.Resources` (which is a map of `genericResource` keyed on the APIGroup/kind).
Fix `resourceKindMap.addResource()` to not assume every Kind has an APIGroup.
> FWI-2422: Fix `resourceKindMap.addResource()` to not assume every Kind has an APIGroup

- pkg/validator/output.go
This PR fixes #768 
NOTE: the master branch of the upstream repository contains some broken code which results in a stack trace when trying to audit manifests (`panic: cannot deep copy int`), so better to checkout my commit while building, it's branched out from `7.0.1`.
The goal is to suppress references to resources containing empty results when `--only-show-failed-tests` is passed.
Similarly to `GetPrettyOutput`, each struct has a method that verifies whether the respective `ResultSet` is empty. Empty results are removed from `AuditData`.
-
> Suppress empty results when --only-show-failed-tests is passed

- checks/clusterrolebindingClusterAdmin.yaml
- checks/rolebindingClusterAdminClusterRole.yaml
- checks/rolebindingClusterAdminRole.yaml
- pkg/config/checks.go
- test/checks/clusterrolebindingClusterAdmin/failure.all_verbs.yaml
- test/checks/clusterrolebindingClusterAdmin/failure.all_verbs_different_order.yaml
- test/checks/clusterrolebindingClusterAdmin/failure.default_clusteradmin_clusterrole.yaml
- test/checks/clusterrolebindingClusterAdmin/failure.wildcards.yaml
- test/checks/clusterrolebindingClusterAdmin/success.allow_unrelated_perms.yaml
- test/checks/clusterrolebindingClusterAdmin/success.explicit_apigroups.yaml
- test/checks/clusterrolebindingClusterAdmin/success.explicit_resources.yaml
- test/checks/clusterrolebindingClusterAdmin/success.explicit_verbs.yaml
- test/checks/rolebindingClusterAdminClusterRole/failure.all_verbs.yaml
- test/checks/rolebindingClusterAdminClusterRole/failure.all_verbs_different_order.yaml
- test/checks/rolebindingClusterAdminClusterRole/failure.default_clusteradmin_clusterrole.yaml
- test/checks/rolebindingClusterAdminClusterRole/failure.wildcards.yaml
- test/checks/rolebindingClusterAdminClusterRole/success.allow_unrelated_perms.yaml
- test/checks/rolebindingClusterAdminClusterRole/success.binding_references_role.yaml
- test/checks/rolebindingClusterAdminClusterRole/success.explicit_apigroups.yaml
- test/checks/rolebindingClusterAdminClusterRole/success.explicit_resources.yaml
- test/checks/rolebindingClusterAdminClusterRole/success.explicit_verbs.yaml
- test/checks/rolebindingClusterAdminRole/failure.all_verbs.yaml
- test/checks/rolebindingClusterAdminRole/failure.all_verbs_different_order.yaml
- test/checks/rolebindingClusterAdminRole/failure.wildcards.yaml
- test/checks/rolebindingClusterAdminRole/success.allow_unrelated_perms.yaml
- test/checks/rolebindingClusterAdminRole/success.binding_references_clusterrole.yaml
- test/checks/rolebindingClusterAdminRole/success.explicit_apigroups.yaml
- test/checks/rolebindingClusterAdminRole/success.explicit_resources.yaml
- test/checks/rolebindingClusterAdminRole/success.explicit_verbs.yaml
- test/fixtures.go
Add new checks that alert when:
* A ClusterRoleBinding references the default `cluster-admin` ClusterRole, or another role with wildcard permissions.
* A RoleBinding references the default `cluster-admin` ClusterRole, or another role with wildcard permissions.
* A RoleBinding references a Role with wildcard permissions.
Note that "wildcard permissions" also includes the literal specification of all 7 verbs.
> FWI-2582: Add `clusterrolebindingClusterAdmin`, `rolebindingClusterAdminRole`, and `rolebindingClusterAdminClusterRole` checks + schema tests

- cmd/polaris/webhook.go
- pkg/validator/schema.go
This PR fixes https://github.com/FairwindsOps/polaris/issues/838
Log a warning message instead of panicking when there's a multi-resource check enabled in admission
Also added a flag for the cert dir
> Add warning message for multi-schema checks in admission

- .circleci/config.yml
* Add tag-filters to the rest of the job in the CircleCI workflow, so the workflow runs when a tag is pushed.
* Re-enable docs build/push after goreleaser/CI updates.
> Fix CI tag filters and re-enable docs

- checks/topologySpreadConstraint.yaml
- docs/checks/reliability.md
- examples/config.yaml
- pkg/config/checks.go
- test/checks/topologySpreadConstraint/failure.invalidtopologykey.yaml
- test/checks/topologySpreadConstraint/failure.nospreadconstraint.yaml
- test/checks/topologySpreadConstraint/success.yaml
This PR fixes #547
See issue #547 - Add a check for pod topologySpreadConstraints - recommending that users set these to ensure high availability across zones and/or hosts
Add topologySpreadConstraint check
There may be more parts of the spec that we want to recommend, and possibly only limit to one topologyKey.
Also, possibly splitting this into two checks - one that ensures a topologySpreadConstraint exists, and another to verify its configuration
> Add a check for topologySpreadConstraint

- checks/dangerousCapabilities.yaml
This PR fixes an issue where the mutation for `dangerousCapabilities` interferes with the mutation for `insecureCapabilities`
Make mutation for dangerousCapabilities more specific
There's a larger issue where mutations run in a non-deterministic order. There's also no defense against mutations doing conflicting or even opposite things (e.g. one might set cpu limits, and another remove cpu limits).
> Fix conflict between dangerousCapabilities and insecureCapabilities

- cmd/polaris/audit.go
This PR fixes #908 
The goal is to fix the helm chart auditing so it works for what I am wanting to do today (also makes it work per [the docs](https://github.com/FairwindsOps/polaris/blob/master/docs/infrastructure-as-code.md#audit-helm-charts)).
I change the helm template command to have helm generate a release name instead of using the helm chart path as the release name (which is frequently not a valid release name).
You may want to hard-code the release name to something more self-explanatory if it shows up in the output like `polarisReleaseName`.
I tested the changes locally, and Polaris audit now works instead of breaking quickly. Note, I also ran `go test`.
> Fix #908 by generating release name

- cmd/polaris/audit.go
> Skip https certificate verification

- go.mod
- go.sum
> Bump golang.org/x/net from 0.6.0 to 0.7.0

- .github/actions/setup-polaris/Dockerfile
- .github/actions/setup-polaris/get_polaris.sh
- .github/workflows/stale.yml
- .github/workflows/test_setup.yml
Several of the workflows in this repository (both internal and the setup polaris action exposed externally) are affected by deprecation warnings by Github.
This PR resolves all deprecation warnings by bumping third party workflows used, as well as some syntax changes in the setup-polaris workflow.
As of now I don't see any other ways to resolve these deprecation warnings.
> chore(ci): Upgrade Github CI/CD to non-deprecated actions

- docs/changelog.md
- docs/checks/reliability.md
- docs/checks/security.md
- examples/config-full.yaml
- examples/config.yaml
This PR fixes internal #FWI-4250
- Change all ignore checks to warning
- Change the ones that say "These are initially warning and will later be promoted to danger." to danger
- Publish a new major version of Polaris
Updated severity for some checks and update documentation for those checks and out-dated changelog
N/A
> Update checks severities

- cmd/polaris/audit.go
- redirect user to cluster action-items instead of cluster overview
> Redirect user to cluster action-items instead of cluster overview

- pkg/auth/login.go
When leaving the TCP listener "open", `macos` will prompt the user for permission. By setting it to `localhost` it does not
> tweak net listener to localhost - removing unwanted popup

- cmd/polaris/webhook.go
This PR fixes an issue where the webhook server can't find certs. Introduced in 8.1 via https://github.com/FairwindsOps/polaris/pull/951/files#diff-19034316a5a02110439c93752c79380bc51d15f761e35c171dba963947046a20R27-R58
Fix webhook certificate handling
Pass certDir option to the right place
> fix cert dir arg

- pkg/config/checks.go
- pkg/config/checks_test.go
Adds test for required fields on built-in checks
> add test for required fields on built-in checks

- cmd/polaris/audit.go
- docs/cli.md
- pkg/validator/output.go
To address https://github.com/FairwindsOps/polaris/issues/754, I've chosen to implement verbosity options for displaying audit results in the same manner as log levels. `danger` is the least verbose option and will only include results of that severity. `warning` is the medium verbosity option and will only display results of severity `warning` or `danger`. By default, all results will be displayed. This will still function with `--only-show-failed-tests` and behave as expected.
Add verbosity options to the `audit` subcommand in the polaris CLI
Low verbosity (`danger`)
```
./polaris audit --audit-path=manifests --severity=danger | wc -l
Want more? Automate Polaris for free with Fairwinds Insights!
🚀 https://fairwinds.com/insights-signup/polaris 🚀
116
```
Medium verbosity …
> Add option to filter audit results by severity level

- cmd/polaris/audit.go
- docs/cli.md
This PR fixes #985
not to render and audit test manifests
add `helm-skip-tests` flag to `audit` command
> Add helm-skip-tests flag

- pkg/config/schema.go
- test/checks/resourceRange/check.yaml
- test/checks/resourceRange/failure.cpu-number.yaml
- test/checks/resourceRange/failure.mem-number.yaml
- test/checks/resourceRange/success.cpu-number.yaml
- test/checks/resourceRange/success.mem-number.yaml
This PR fixes an issue when parsing numerical resource ranges
Fixes issue https://github.com/FairwindsOps/polaris/issues/979
This one was really hard to track down. It actually doesn't trip up our tests, because we parse and validate known Kinds properly. The issue seems to be for unknown resources like the BuildConfig referenced in #979 
I've validated that the case provided in the issue now works.
Support numerical CPU and memory amounts
Add a case to handle numbers
> Fix numerical resource ranges

- checks/clusterrolebindingClusterAdmin.yaml
- checks/rolebindingClusterAdminClusterRole.yaml
- checks/rolebindingClusterRolePodExecAttach.yaml
- checks/rolebindingRolePodExecAttach.yaml
- go.mod
- test/checks/rolebindingClusterAdminClusterRole/success.role_with_no_cluster_roles.yaml
- test/checks/rolebindingClusterRolePodExecAttach/success.role_with_no_cluster_roles.yaml
- test/checks/rolebindingRolePodExecAttach/success.role_with_no_cluster_roles.yaml
This PR fixes #1003
Polaris checks utilize `additionalSchemaStrings`, an additional section of jsonschema that will only evaluate if the object conforms to `schemaString`. The conditional statements in `additionalSchemaStrings` need to be arranged in a manner such that when there's nothing to evaluate, the string is empty (not the object therein).
Fix false positives reported when running the Polaris CLI for the following checks:
* clusterrolebindingClusterAdmin
* rolebindingClusterAdminClusterRole
* rolebindingClusterRolePodExecAttach
* rolebindingRolePodExecAttach
adjust the ordering of conditional expressions in `additionalSchemaStrings`:
e.g.
```
additionalSchemaStrings:
rbac.authorization.k8s.io/ClusterRole: |
-    type: object
-    # This schema is validated for all roleBindings, …
```
> FWI-5232 Conditional expressions should be at very top of additionalSchemaStrings

- checks/missingPodDisruptionBudget.yaml
- test/checks/missingPodDisruptionBudget/failure.wrong-place.yaml
- test/checks/missingPodDisruptionBudget/success.many.yaml
The PDB's `matchLabels` should match the labels on the _pod_, not the deployment. Looks like we were checking the latter. This fixes it.
Small tweak to the schema, added tests
> fix missing PDB check

- pkg/mutation/mutate.go
- pkg/mutation/mutate_test.go
This PR fixes internal FWI-5836
On YAML mutations, we should keep original comment if override is not provided for scalar values
> FWI-5836 - Keep original comment if override is not provided

- test/checks/pdbDisruptionsIsZero/success.both.yaml
- test/checks/pdbDisruptionsIsZero/success.min.yaml
This PR fixes typos
- fix typo for `minAvailable` and `maxAvailable`
> fix typo for minAvailable and maxAvailable

- docs/changelog.md
- docs/checks/reliability.md
- pkg/config/checks.go
- pkg/config/checks/hpaMaxAvailability.yaml
- pkg/config/checks/hpaMinAvailability.yaml
- pkg/config/default.yaml
- pkg/config/examples/config-full.yaml
- pkg/kube/resources.go
- pkg/validator/functions.go
- pkg/validator/schema.go
- pkg/validator/validations.go
- test/checks/hpaMaxAvailability/failure.yaml
- test/checks/hpaMaxAvailability/success.minAvailabilityAbsent.yaml
- test/checks/hpaMaxAvailability/success.yaml
- test/checks/hpaMinAvailability/failure.yaml
- test/checks/hpaMinAvailability/success.minReplicaAbsent.yaml
- test/checks/hpaMinAvailability/success.yaml
- test/fixtures.go
- test/schema_test.go
This PR fixes internal INSIGHTS-90
- implement support for HPA `minAvailable` check
- implement support for HPA `maxAvailable` check
- I had to implement a custom validator function for validations that are not supported by JSON validation
- i.e.: in HPA `maxAvailable` check, we need to check fix `maxAvailable` is greater than `minAvailable` and in JSON validation you cannot self-reference fields
> INSIGHTS-90 - implement HPA minAvailable and HPA maxAvailable checks

- docs/changelog.md
> fix changelog for release

- pkg/validator/pdb_hpa_validator.go
- test/checks/pdbMinAvailableGreaterThanHPAMinReplicas/success-maxUnavailable.yaml
By spec, `minAvailable` is optional, and we should accommodate for that
This PR fixes #1061
> pdbMinAvailableGreaterThanHPAMinReplicas should support optional minAvailable

- .circleci/config.yml
- .goreleaser.yml.envsubst
- go.mod
- scripts/goreleaser.sh
> Updated Go to 1.22.7 to fix vulnerabilities

- pkg/config/checks/rolebindingRolePodExecAttach.yaml
- test/checks/rolebindingRolePodExecAttach/success.role_binding_cluster_role_binding.yaml
Fix the case of a RoleBinding that points to a ClusterRole.
In that case, we ignore the RoleBinding validation altogether since it will be evaluated by the rolebindingClusterRolePodExecAttach check.
This PR fixes the rolebindingRolePodExecAttach check
Fix the check of a RoleBinding that references a Role allowing pods/exec or pods/attach in the case that it points to a ClusterRole. 
Modify the kind field value of the roleRef field of the RoleBinding from "Role" to "ClusterRole" in the schemaString
NA
> Fix: rolebindingRolePodExecAttach check
