FairwindsOps/polaris

deploy/helm/polaris/templates/webhook.rbac.yaml, deploy/webhook.yaml
=> Fixing webhook rbac namespacing

pkg/validator/container.go, pkg/validator/container_test.go, pkg/validator/pod.go
=> Ensuring that readiness probes in init containers are not validated

pkg/dashboard/dashboard.go
Awesome project! It works for me with a `port-forward`, but not with `-dashboard-path-prefix`. After this change I can load the dashboard with a base path (`/polaris/` in my case), but I haven't tested building a Docker image for my cluster yet. 
~~Btw, I was unable to sign the CLA at https://cla-assistant.io/fairwinds/polaris (404)~~ With `?pullRequest=201` I could sign the CLA.
=> pkg/dashboard: setup basePath as a path prefix in routing

pkg/validator/container.go, pkg/validator/container_test.go, pkg/validator/controller.go, pkg/validator/controller_test.go, pkg/validator/fullaudit_test.go, pkg/validator/pod.go, pkg/validator/pod_test.go, pkg/webhook/validator.go, test/fixtures.go
Fixes #215 and #209 
Also skips resource checks if they're not in the config
=> skip health checks for jobs, cronjobs, and initContainers

.circleci/config.yml
This should fix the issue with dependabot
=> don't push docker images on forked PRs

pkg/validator/summary.go
Accidentally pushed this to master initially 😬 
Reverted and opened here.
=> sort results on dashboard

.circleci/config.yml, README.md, cmd/polaris/audit.go, deploy/dashboard.yaml, deploy/webhook.yaml, docs/check-documentation/images.md, docs/check-documentation/resources.md, docs/check-documentation/security-capabilities.md, docs/check-documentation/security.md, docs/exit-codes.md, docs/usage.md, examples/config-full.yaml, examples/config.yaml, examples/output.json, pkg/config/severity.go, pkg/dashboard/assets/css/dashboard.css, pkg/dashboard/assets/js/charts.js, pkg/dashboard/helpers.go, pkg/dashboard/templates/dashboard.gohtml, pkg/validator/container_test.go, pkg/validator/controller_test.go, pkg/validator/fullaudit_test.go, pkg/validator/pod_test.go, pkg/validator/schema_test.go, pkg/validator/summary.go, pkg/webhook/webhook.go
This puts us a little more in-line with Insights, and I think is a better indication of what's happening (error sounds like something went wrong, rather than something, well, dangerous).
=> Change error to danger

.circleci/config.yml, go.mod, go.sum
Something's up with goreleaser...hopefully this fixes it.
=> fix dependencies

pkg/kube/workload.go
=> handle case where RBAC is missing for a CRD

go.sum, pkg/kube/workload.go
🤦 pretty sure this was my fault
=> catch cache error

pkg/dashboard/assets/css/dashboard.css, pkg/dashboard/assets/js/filter.js, pkg/dashboard/dashboard.go, pkg/dashboard/helpers.go, pkg/dashboard/templates/dashboard.gohtml
This branch implements Namespace Filters in the dashboard, addressing [this issue](https://github.com/FairwindsOps/polaris/issues/123).
I would appreciate some feedback on the styling of the Namespace Filter section, and so I am considering this a work in progress pending style updates.
Edit: Removed WIP after suggested style updates
=> Filter by Namespace on Dashboard

docs/usage.md
Dashboard run option as docker container
=> "install" option as docker container

pkg/dashboard/templates/dashboard.gohtml
Had a double close tag. :shakesfist: XML!
=> fix html tag

pkg/dashboard/helpers_test.go
Added passing test for the following helpers.go methods:
- getGrade
- getWeatherIcon
=> Add tests for getWeatherIcon and getGrade helper methods

pkg/dashboard/helpers_test.go
Add test for all helper methods
=> Helper tests2

test/checks/memoryLimitsMissing/failure.yaml, test/checks/memoryLimitsMissing/success.yaml, test/checks/memoryRequestsMissing/failure.yaml, test/checks/memoryRequestsMissing/success.yaml
Success/Failure checks tests for the following checks:
memoryRequestsMissing
memoryLimitsMissing
=> add memory limits and requests success/failure tests

test/checks/tagNotSpecified/failure.latest.yaml, test/checks/tagNotSpecified/failure.yaml, test/checks/tagNotSpecified/success.yaml
add passing failure, failure.latest and success.yaml tests
=> add failure, failure.latest and success.yaml file

CODEOWNERS, checks/notReadOnlyRootFilesystem.yaml, test/checks/notReadOnlyRootFilesystem/failure.pod.yaml, test/checks/notReadOnlyRootFilesystem/failure.two_cont_one_unspecified.yaml, test/checks/notReadOnlyRootFilesystem/success.pod.yaml, test/schema_test.go
Update file check to include good and bad security context
=> update notReadOnlyRootFilesystem check

.github/actions/setup-polaris/get_polaris.sh, .github/workflows/test_setup.yml, docs/infrastructure-as-code.md
Closes: https://github.com/FairwindsOps/polaris/issues/659
Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>
=> Correct URL to download Polaris tar

checks/cpuLimitsMissing.yaml, checks/cpuRequestsMissing.yaml, checks/deploymentMissingReplicas.yaml, checks/hostIPCSet.yaml, checks/hostNetworkSet.yaml, checks/hostPIDSet.yaml, checks/hostPortSet.yaml, checks/livenessProbeMissing.yaml, checks/memoryLimitsMissing.yaml, checks/memoryRequestsMissing.yaml, checks/priorityClassNotSet.yaml, checks/readinessProbeMissing.yaml, checks/runAsPrivileged.yaml, checks/runAsRootAllowed.yaml, pkg/validator/schema.go, test/checks/cpuLimitsMissing/success.yaml, test/checks/cpuRequestsMissing/success.yaml, test/checks/livenessProbeMissing/failure.yaml, test/checks/memoryRequestsMissing/success.yaml, test/checks/readinessProbeMissing/failure.yaml, test/mutation_test.go, test/schema_test.go
=> Added more mutations and refactor test to test each mutation separately

checks/cpuLimitsMissing.yaml, checks/cpuRequestsMissing.yaml, checks/memoryLimitsMissing.yaml, checks/memoryRequestsMissing.yaml, checks/runAsRootAllowed.yaml, pkg/mutation/mutate.go
Makes some of the mutations more robust
Ensure paths exist when doing the `add` operation
=>  ensure path exists when adding mutations

test/webhook_test.sh
=> fix webhook test

cmd/polaris/fix.go, pkg/validator/schema.go
To add two flags
- `check` flag to only fix specific checks and ignore others with `check=all` fixing all defined mutations
-
=> Add `checks` flag  to fix specific checks

checks/dangerousCapabilities.yaml, checks/insecureCapabilities.yaml, checks/notReadOnlyRootFilesystem.yaml, test/checks/cpuLimitsMissing/mutated.yaml, test/checks/dangerousCapabilities/failure.yaml, test/checks/dangerousCapabilities/mutated.yaml, test/checks/insecureCapabilities/mutated.drop-most.yaml, test/checks/insecureCapabilities/mutated.yaml, test/checks/memoryLimitsMissing/failure.cpu.yaml, test/checks/memoryLimitsMissing/mutated.cpu.yaml, test/checks/memoryLimitsMissing/mutated.yaml, test/mutation_test.go, test/schema_test.go
* Add a few more good mutations
* Fix the mutation tests
=> Add more mutations, fix mutation tests

fairwinds-insights.yaml
=> Update org name in fairwinds-insights.yaml

docs/changelog.md, docs/customization/custom-checks.md, main.go
=> update changelog and docs

docs/customization/custom-checks.md
Update docs to reflect PR #801, `target: PodTemplate` + that template being available in the go template variable `Polaris.PodTemplate`.
=> Update docs to reflect `target: PodTemplate` RE: PR #801

checks/sensitiveConfigmapContent.yaml, checks/sensitiveContainerEnvVar.yaml, examples/config-full.yaml, pkg/config/checks.go, test/checks/sensitiveConfigmapContent/failure.key_aws_secret_access_key.yaml, test/checks/sensitiveConfigmapContent/failure.key_azure_batch_key.yaml, test/checks/sensitiveConfigmapContent/failure.key_oci_cli_key_content.yaml, test/checks/sensitiveConfigmapContent/failure.key_password.yaml, test/checks/sensitiveConfigmapContent/failure.value_private_key.yaml, test/checks/sensitiveConfigmapContent/success.no_data.yaml, test/checks/sensitiveConfigmapContent/success.valid_keys_and_values.yaml, test/checks/sensitiveContainerEnvVar/failure.key_aws_secret_access_key.yaml, test/checks/sensitiveContainerEnvVar/failure.key_azure_batch_key.yaml, test/checks/sensitiveContainerEnvVar/failure.key_oci_cli_key_content.yaml, test/checks/sensitiveContainerEnvVar/failure.key_password.yaml, test/checks/sensitiveContainerEnvVar/failure.value_private_key.yaml, test/checks/sensitiveContainerEnvVar/success.no_env_vars.yaml, test/checks/sensitiveContainerEnvVar/success.valid_env_vars.yaml, test/fixtures.go
Add checks to detect potentially sensitive content in the keys and values of container environment variables and ConfigMap data.
=> FWI-2509: Add sensitiveContainerEnvVar and sensitiveConfigMapContent checks

cmd/polaris/root.go, pkg/validator/schema.go
Add debug-logging to improve troubleshooting of JSON Schema.
=> FWI-2912: Add logging to improve debugging of JSON Schema

Dockerfile
=> update alpine to latest edge

README.md
This PR updates documentation based on our template.
Update documentation
=> Update documentation from template

docs/admission-controller.md, docs/checks/reliability.md, docs/checks/security.md, examples/config-full.yaml, examples/config.yaml
update checks page with newer checks. Make sure config-full.yaml has all of the checks in config.yaml. Update list of checks that can be mutated.
=> Update checks documentation

Dockerfile
Update alpine
Update dockerfile
=> move to latest alpine

cmd/polaris/audit.go
- improve `audit` `--cluster-name` flag description
=> improve cluster-name flag description

checks/automountServiceAccountToken.yaml, checks/clusterrolebindingClusterAdmin.yaml, checks/clusterrolebindingPodExecAttach.yaml, checks/sensitiveContainerEnvVar.yaml, pkg/config/schema.go, test/checks/automountServiceAccountToken/success.no_serviceaccount.yaml, test/checks/insecureCapabilities/failure.add.yaml, test/checks/insecureCapabilities/mutated.add.yaml, test/mutation_test.go
This PR fixes a couple minor issues when scanning IaC with the new checks
=> Minor fixes for NSA checks

checks/metadataAndNameMismatched.yaml, checks/priorityClassNotSet.yaml, docs/admission-controller.md, docs/changelog.md, docs/checks/reliability.md, test/mutation_test.go
Add / fix checks category
`Category` was missing/wrong for some checks, this PR fixes it
=> FWI-4307 - fix checks category

cmd/polaris/audit.go
=> feat: handle multiple values files

pkg/kube/resources.go
Improve how polaris retrieves the workloads 
Using controller-utils to retrieve controllers
=> Using controller-utils to get workloads

Dockerfile
=> Update alpine to 3.19
